### ISSUE TITLE
通过Nginx 反向代理Https出现SELF_URL_PATH配置错误

### ISSUE THREAD

**Issue by pastay** [HenryQW/Awesome-TTRSS#117]
**Bug 描述**
通过Nginx 反向代理Https出现SELF_URL_PATH配置错误，无法启动（通过 域名:181可正常访问）

**部署方法**
 -  docker-compose
 - 使用的镜像版本  latest

**部署环境**
 - 操作系统:  Ubuntu 18.04
 - 浏览器: safari

**复现步骤**
认真阅读了文档，以及相关issue，反复尝试还是出现这种问题

**预期结果**
通过https正常访问

**doker-compose配置**

```
version: "3"
services:
  database.postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=rrttrssrr! # please change the password
    volumes:
      - ~/postgres/data/:/var/lib/postgresql/data # persist postgres data to ~/postgres/data/ on the host
    restart: always

  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 181:80
    environment:
      - SELF_URL_PATH=http://个人域名:181/ 
      - DB_HOST=database.postgres
      - DB_PORT=5432
      - DB_NAME=ttrss
      - DB_USER=postgres
      - DB_PASS=rrttrssrr!
      - ENABLE_PLUGINS=auth_internal,fever # auth_internal is required. Plugins enabled here will be enabled for all users as system plugins
    stdin_open: true
    tty: true
    restart: always
    command: sh -c 'sh /wait-for.sh $$DB_HOST:$$DB_PORT -- php /configure-db.php && exec s6-svscan /etc/s6/'

  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    expose:
      - 3000
    restart: always

  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      - NODE_ENV=production
    expose:
      - 3000
    restart: always
```

**nginx配置文件**  /etc/nginx/conf.d/ttrss.conf

```
upstream ttrssdev {
  server 127.0.0.1:181;
}

server {
    listen 80;
    server_name  myrss.ml;
    return 301 https://myrss.ml$request_uri;
}

server {
    listen 443 ssl;
    gzip on;
    server_name  myrss.ml;

    ssl_certificate /etc/letsencrypt/live/个人域名/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/个人域名/privkey.pem;

    access_log /var/log/nginx/ttrssdev_access.log combined;
    error_log  /var/log/nginx/ttrssdev_error.log;

    location / {
        proxy_redirect off;
        proxy_pass http://ttrssdev;

        proxy_set_header  Host                $http_host;
        proxy_set_header  X-Real-IP           $remote_addr;
        proxy_set_header  X-Forwarded-Ssl     on;
        proxy_set_header  X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto   $scheme;
        proxy_set_header  X-Frame-Options     SAMEORIGIN;

        client_max_body_size        100m;
        client_body_buffer_size     128k;

        proxy_buffer_size           4k;
        proxy_buffers               4 32k;
        proxy_busy_buffers_size     64k;
        proxy_temp_file_write_size  64k;
    }
}
```

请问是否哪里的配置出现了问题吗？

![批注 2020-01-12 175925](https://user-images.githubusercontent.com/21967597/72217140-88b8c180-3565-11ea-9304-fda92d886a46.jpg)

**其他**
已经尝试过将SELF_URL_PATH替换成ip127.0.0.1或者https://域名 均无法解决问题
