### ISSUE TITLE
TTRSS 页面跳转错误

### ISSUE THREAD

**Issue by PorridgePi** [HenryQW/Awesome-TTRSS#133]
**Bug 描述**
TTRSS 页面跳转错误。先开始提示SELF_URL_PATH错误，更改后便出现了这个问题。

**你谷歌/百度了吗？**
在网上搜了，但没有跟我相似的案例。

**部署方法**
 - docker-compose
 - version: latest

**部署环境**
 - OS: Ubuntu 18.04.4 LTS
 - Server: Azure VM
 - Browser: Chrome

**复现步骤**
复现该 bug 的详细步骤: 
1. Tiny Tiny RSS 提示 SELF_URL_PATH 错误。
2. 于是，我把SELF_URL_PATH改成了网页上显示的链接。
3. 登录页面能显示出来，但是点击登录后却跳转至主页面了。
4. 我的TTRSS用Nginx反向代理到 https://website.com/rss 但按登录后就跳转至 https://website.com/。
5. 过一会后，访问 https://website.com/rss 却发现已经登录进去了。

**预期结果**
帐号登录成功并跳转到主页面

**截屏**
无

**错误日志**
无

**其他**
之前我部署在 https://website.com/ 时，可以正常访问。

docker-compose.yml:
```
version: "3"
services:
  database.postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password # please change the password
    volumes:
      - ~/postgres/data/:/var/lib/postgresql/data # persist postgres data to ~/postgres/data/ on the host
    restart: always

  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 181:80
    environment:
      - SELF_URL_PATH=https://website.com/ # please change to your own domain
      - DB_HOST=database.postgres
      - DB_PORT=5432
      - DB_NAME=ttrss
      - DB_USER=postgres
      - DB_PASS=password # please change the password
      - ENABLE_PLUGINS=auth_internal,fever # auth_internal is required. Plugins enabled here will be enabled for all users as system plugins
    stdin_open: true
    tty: true
    restart: always
    command: sh -c 'sh /wait-for.sh $$DB_HOST:$$DB_PORT -- php /configure-db.php && exec s6-svscan /etc/s6/'

  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    expose:
      - 3000
    restart: always

  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      - NODE_ENV=production
    expose:
      - 3000
    restart: always

#  utility.watchtower:
#    container_name: watchtower
#    image: containrrr/watchtower:latest
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    environment:
#      - WATCHTOWER_CLEANUP=true
#      - WATCHTOWER_POLL_INTERVAL=86400
#    restart: always
```
Nginx reverse-proxy.conf:
```
upstream ttrssdev {
    server 127.0.0.1:181;
}

server {
    listen 80;
    server_name website.com
    return 301 https://website.com$request_uri;
}

server {
    listen 443 ssl;
    gzip on;
    server_name website.com;

    ssl_certificate /etc/letsencrypt/live/website.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/website.com/privkey.pem;

    access_log /var/log/nginx/ttrssdev_access.log combined;
    error_log  /var/log/nginx/ttrssdev_error.log;

    location /rss/ {
        proxy_redirect off;
        rewrite /rss/(.*) /$1 break;
        proxy_pass http://ttrssdev ;

        proxy_set_header  Host                $http_host;
        proxy_set_header  X-Real-IP           $remote_addr;
        proxy_set_header  X-Forwarded-Ssl     on;
        proxy_set_header  X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto   $scheme;
        proxy_set_header  X-Frame-Options     SAMEORIGIN;

        client_max_body_size        100m;
        client_body_buffer_size     128k;

        proxy_buffer_size           4k;
        proxy_buffers               4 32k;
        proxy_busy_buffers_size     64k;
        proxy_temp_file_write_size  64k;
    }


    location /couchdb/ {
        rewrite /couchdb/(.*) /$1 break;
        proxy_pass http://localhost:5984;
        proxy_redirect off;
        proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```
