### ISSUE TITLE
[BUG] 无法正常注销

### ISSUE THREAD

**Issue by madordie** [HenryQW/Awesome-TTRSS#190]
**Bug 描述**
点击`注销`按钮,跳转到一个错误页面

**你谷歌/百度了吗？**
由于没有发现什么错误、提示信息,并不能搜索到相关信息

**部署方法**
 - docker-compose.yml
```yml
version: "3"
services:
  database.postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=my-db-pass# please change the password
    volumes:
      - ~/postgres/data/:/var/lib/postgresql/data # persist postgres data to ~/postgres/data/ on the host
    restart: always
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 181:80
    environment:
      - SELF_URL_PATH=https://my.host.net/ # please change to your own domain
      - DB_HOST=database.postgres
      - DB_PORT=5432
      - DB_NAME=ttrss
      - DB_USER=postgres
      - DB_PASS=my-db-pass # please change the password
      - ENABLE_PLUGINS=auth_internal,fever,api_feedreader # auth_internal is required. Plugins enabled here will be enabled for all users as system plugins
      - FEED_LOG_QUIET=true
    stdin_open: true
    tty: true
    restart: always
    command: sh -c 'sh /wait-for.sh $$DB_HOST:$$DB_PORT -- php /configure-db.php && exec s6-svscan /etc/s6/'
```
 - nginx.conf
```conf
    server {
        ...
        location /ttrss/ {
            rewrite /ttrss/(.*) /$1 break;
            proxy_redirect https://$http_host https://$http_host/ttrss;
            proxy_pass http://localhost:181;

            proxy_set_header  Host                $http_host;
            proxy_set_header  X-Real-IP           $remote_addr;
            proxy_set_header  X-Forwarded-Ssl     on;
            proxy_set_header  X-Forwarded-For     $proxy_add_x_forwarded_for;
            proxy_set_header  X-Forwarded-Proto   $scheme;
            proxy_set_header  X-Frame-Options     SAMEORIGIN;

            client_max_body_size        100m;
            client_body_buffer_size     128k;

            proxy_buffer_size           4k;
            proxy_buffers               4 32k;
            proxy_busy_buffers_size     64k;
            proxy_temp_file_write_size  64k;
        }
  }
```

**部署环境**
 - CentOS Linux release 7.8.2003 (Core)
 - Chrome 版本 85.0.4183.121（正式版本） （64 位）

**复现步骤**
复现该 bug 的详细步骤
1. 打开 浏览器,输入 ttrss地址: [https://my.host.net/ttrss](http://localhost)
2. 登录之后,自动重定向到[https://my.host.net/ttrss/#f=-3&c=0](http://localhost)
3. 点击`右上角菜单`   展开之后点击 `注销`
4.  发现错误: URL重定向到[https://my.host.net/public.php](http://localhost)

**预期结果**
能正常注销, 回到首页

**错误日志**
并没有什么错误
```sh
$ docker logs ttrss --tail 100
[27-Sep-2020 02:22:16] NOTICE: fpm is running, pid 18
[27-Sep-2020 02:22:16] NOTICE: ready to handle connections
```
**其他**
- 没有升级pg13的时候就挂了
- 升级完pg13的时候第一次好像注销成功了, 但是恢复完数据就GG了
- [https://my.host.net/ttrss/public.php](http://localhost): `{"error":{"code":13,"message":null}}`
