### ISSUE TITLE
[BUG]Nginx 通过网站子目录进行反向代理无法访问链接

### ISSUE THREAD

**Issue by Chuyukang** [HenryQW/Awesome-TTRSS#231]
**Bug 描述**
Nginx 通过网站子目录进行反向代理，点击文章链接转向http://ip/backend.php 显示405 Not Allowed

**你谷歌/百度了吗？**
使用谷歌未找到相关资料

**部署方法**
 - Docker 或 docker-compose
 - 使用的镜像版本latest

**部署环境**
 - 操作系统: Ubuntu 18.04
 - 浏览器: chrome

**复现步骤**
复现该 bug 的详细步骤
1. 按照文档中使用子目录反向代理的方法配置nginx，设置rewrite, proxy_redirect, proxy_pass，参考#135
2. 设置SELF_URL_PATH=http://ip/ （设置为“http://ip/ttrss/”启动失败
3. 点击文章，跳转至"http://ip/backend.php" 并显示405 Not Allowed

**预期结果**
点击文章应跳转至相应文章链接。

**截屏**
如果可以提供截屏将有助于 bug 修复。

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。

**其他**
nginx配置
```
location /ttrss/ {
                        rewrite ^/ttrss/(.*)$ /$1 break;
                        proxy_redirect http://$http_host http://$http_host/ttrss;
                        proxy_pass http://localhost:181;

                        proxy_set_header  Host                $http_host;
                        proxy_set_header  X-Real-IP           $remote_addr;
                        proxy_set_header  X-Forwarded-Ssl     on;
                        proxy_set_header  X-Forwarded-For     $proxy_add_x_forwarded_for;
                        proxy_set_header  X-Forwarded-Proto   $scheme;
                        proxy_set_header  X-Frame-Options     SAMEORIGIN;

                        client_max_body_size        100m;
                        client_body_buffer_size     128k;

                        proxy_buffer_size           4k;
                        proxy_buffers               4 32k;
                        proxy_busy_buffers_size     64k;
                        proxy_temp_file_write_size  64k;
 }
```
docker-compose.yml
```yml
version: "3"
services:
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 181:80
    environment:
      - SELF_URL_PATH=http://ip/ # please change to your own domain
```
