### ISSUE TITLE
[BUG] Upstream ENV changes which might break databse connection and other things

### ISSUE THREAD

**Issue by yche2990** [HenryQW/Awesome-TTRSS#267]
It shows

Exception while creating PDO object:SQLSTATE[08006] [7] could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

**Comment by FaintGhost** [comment]
same here

**Comment by hartzan** [comment]
Could it be this one:**ENV DB_HOST=database.postgres** in Dockerfile? If you are using different name for pg service it doesn't connect? I'm unable to use database.postgres as myservice name in docker swarm??

**Comment by ptsa** [comment]
是上游的config 有更改造成的

**Comment by dimon222** [comment]
Yep, breaking changes keep coming on daily basis to upstream tt-rss, I suggest to park your compose back on Feb 14 tag for next 1 month at least.

PS, this bug is due to this. Yeah, breaking change was announced in forums just 16 hours ago 🥇 
https://community.tt-rss.org/t/rip-config-php-hello-classes-config-php/4337

**Comment by HenryQW** [comment]
Yeah I would disable watchtower for now and use a stable build, `wangqiru/ttrss:latest-2021-02-23` for php8 or `wangqiru/ttrss:latest-2021-02-14` for php7.

Too many changes to cope and the ENV system is being  restruactred to be more docker friendly, but it will affect many things including the support for non-standard(80,443) port feeds which is being circumvented in this repo.

I will be able to work on this after my next ddl on Thursday, any help is appreciated.

**Comment by dimon222** [comment]
@HenryQW I know you mentioned migration to env variables completely. Did u reach some stage or still waiting stabilization on ttrss side (which might never happen) ? I could contribute if needed.

Benefits of this setup in awesome-ttrss is sudoless, preinstalled plugins with tunings and mercury coming together.

**Comment by conanyangqun** [comment]
> Yeah I would disable watchtower for now and use a stable build, `wangqiru/ttrss:latest-2021-02-23` for php8 or `wangqiru/ttrss:latest-2021-02-14` for php7.
> 
> Too many changes to cope and the ENV system is being  restruactred to be more docker friendly, but it will affect many things including the support for non-standard(80,443) port feeds which is being circumvented in this repo.
> 
> I will be able to work on this after my next ddl on Thursday, any help is appreciated.

在Macos上，用docker-compose测试了一下，`wangqiru/ttrss:latest-2021-02-23`这个版本仍然报错，但是`wangqiru/ttrss:latest-2021-02-14`可以使用。

**Comment by ptsa** [comment]
我用 wangqiru/ttrss:latest-2021-02-22 会有错误
Constant DAEMON_UPDATE_LOGIN_LIMIT already defined  不用其他用起来正常

**Comment by HenryQW** [comment]
> @HenryQW I know you mentioned migration to env variables completely. Did u reach some stage or still waiting stabilization on ttrss side (which might never happen) ? I could contribute if needed.
> 
> Benefits of this setup in awesome-ttrss is sudoless, preinstalled plugins with tunings and mercury coming together.

I have not been working on this recently. I think it's still being polished. The major change that makes conifg.php optional only came out yesterday.

**Comment by HenryQW** [comment]
The latest build should hopefully be usable now.

**Comment by Nightliss** [comment]
Hi there,

I'm having same issue

![image](https://user-images.githubusercontent.com/30467858/109794675-64f78580-7c16-11eb-863b-75b842a8e675.png)

```yml
version: "3"
services:
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 181:80
    environment:
      - SELF_URL_PATH=http://rpi4:181/ # please change to your own domain
      - DB_PASS=ttrss # use the same password defined in `database.postgres`
      - PUID=1000
      - PGID=1000
    volumes:
      - feed-icons:/var/www/feed-icons/
    networks:
      - public_access
      - service_only
      - database_only
    stdin_open: true
    tty: true
    restart: always

  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    networks:
      - public_access
      - service_only
    restart: always

  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      - NODE_ENV=production
    networks:
      - service_only
    restart: always

  database.postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=ttrss # feel free to change the password
    volumes:
      - ~/postgres/data/:/var/lib/postgresql/data # persist postgres data to ~/postgres/data/ on the host
    networks:
      - database_only
    restart: always

  # utility.watchtower:
  #   container_name: watchtower
  #   image: containrrr/watchtower:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_POLL_INTERVAL=86400
  #   restart: always

volumes:
  feed-icons:

networks:
  public_access: # Provide the access for ttrss UI
  service_only: # Provide the communication network between services only
    internal: true
  database_only: # Provide the communication between ttrss and database only
    internal: true
```

The only thing I changed is SELF_URL_PATH.
