### ISSUE TITLE
[BUG]SQLSTATE[08006] [7] FATAL:  password authentication failed for user "postgres" in /initialize.php:117

### ISSUE THREAD

**Issue by littlecorgi-twk** [HenryQW/Awesome-TTRSS#285]
**Bug 描述**
错误信息：Please set SELF_URL_PATH to the correct value detected for your server: https://ttrss.littlecorgi.top/ (you're using: %SELF_URL_PATH)

![image](https://user-images.githubusercontent.com/20331307/113297858-bc7c3480-932d-11eb-8f52-2571c0d2cb4a.png)

看了置顶的issue，但是还是搞不懂，我已经都修改过了，但是还是报这个错。
```yml
# docker-compose.yml
version: "3"
services:
  database.postgres:
    image: sameersbn/postgresql:latest
#    container_name: postgres
    environment:
      - PG_PASSWORD=ttrss385419 # please change the password
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data # persist postgres data to ~/postgres/data/ on the host
    restart: always

  service.rss:
    image: wangqiru/ttrss:latest-2021-02-14
#    container_name: ttrss
    ports:
      - 9999:80
    environment:
      - SELF_URL_PATH=https://ttrss.littlecorgi.top/ # please change to your own domain
      - DB_HOST=database.postgres
      - DB_PORT=5432
      - DB_NAME=pgsqlTtrss
      - DB_USER=pgsql_ttrss
      - DB_PASS=ttrss385419 # please change the password
      - ENABLE_PLUGINS=auth_internal,fever # auth_internal is required. Plugins enabled here will be enabled for all users as system plugins
    stdin_open: true
    tty: true
    restart: always
    command: sh -c 'sh /wait-for.sh $$DB_HOST:$$DB_PORT -- php /configure-db.php && exec s6-svscan /etc/s6/'

  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
    image: wangqiru/mercury-parser-api:latest
#    container_name: mercury
    expose:
      - 3000
    restart: always

  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
    image: wangqiru/opencc-api-server:latest
#    container_name: opencc
    environment:
      - NODE_ENV=production
    expose:
      - 3000
    restart: always

  # utility.watchtower:
  ##   container_name: watchtower
  #   image: containrrr/watchtower:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_POLL_INTERVAL=86400
  #   restart: always
```

```conf.d
server {
    listen 80;
    server_name  ttrss.littlecorgi.top;
    return 301 https://ttrss.littlecorgi.top$request_uri;
}
server
{
	listen 443 ssl;
    gzip on;
    server_name  ttrss.littlecorgi.top;
    
    ssl_certificate    /www/server/panel/vhost/cert/ttrss.littlecorgi.top/fullchain.pem;
    ssl_certificate_key    /www/server/panel/vhost/cert/ttrss.littlecorgi.top/privkey.pem;
    
    access_log /www/server/nginx/ttrssdev_access.log combined;
    error_log  /www/server/nginx/ttrssdev_error.log;
    
    location / {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:9999;

        proxy_set_header  Host                $http_host;
        proxy_set_header  X-Real-IP           $remote_addr;
        proxy_set_header  X-Forwarded-Ssl     on;
        proxy_set_header  X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto   $scheme;
        proxy_set_header  X-Frame-Options     SAMEORIGIN;

        client_max_body_size        100m;
        client_body_buffer_size     128k;

        proxy_buffer_size           4k;
        proxy_buffers               4 32k;
        proxy_busy_buffers_size     64k;
        proxy_temp_file_write_size  64k;
    }
}
```

**Comment by dimon222** [comment]
Your `command` in `service.rss` doesn't match whatever is shown in example `docker-compose.yml` file, so perhaps your script that you named `configure-db.php` got out of date.
https://github.com/HenryQW/Awesome-TTRSS/blob/main/docker-compose.yml#L3-L21
https://github.com/HenryQW/Awesome-TTRSS/blob/main/Dockerfile#L153

**Comment by littlecorgi-twk** [comment]
> Your `command` in `service.rss` doesn't match whatever is shown in example `docker-compose.yml` file, so perhaps your script that you named `configure-db.php` got out of date or not matching to version that is in current repo.
> https://github.com/HenryQW/Awesome-TTRSS/blob/main/docker-compose.yml#L3-L21
> https://github.com/HenryQW/Awesome-TTRSS/blob/main/Dockerfile#L153

I modified the `docker-compose.yml`. But it except a new problem.  Opening the site shows 502 Bad Gateway.

```
# docker-compose.yml
version: "3"
services:
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 9999:80
    environment:
      - SELF_URL_PATH=https://ttrss.littlecorgi.top/ # please change to your own domain
      - DB_HOST=database.postgres
      - DB_PORT=5432
      - DB_NAME=pgsqlTtrss
      - DB_USER=pgsql_ttrss
      - DB_PASS=ttrss385419 # please change the password
      - PUID=1000
      - PGID=1000
    volumes:
      - feed-icons:/var/www/feed-icons/
    networks:
      - public_access
      - service_only
      - database_only
    stdin_open: true
    tty: true
    restart: always

  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    networks:
      - public_access
      - service_only
    restart: always

  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      - NODE_ENV=production
    networks:
      - service_only
    restart: always

  database.postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=ttrss385419 # feel free to change the password
    volumes:
      - ~/postgres/data/:/var/lib/postgresql/data # persist postgres data to ~/postgres/data/ on the host
    networks:
      - database_only
    restart: always

  # utility.watchtower:
  #   container_name: watchtower
  #   image: containrrr/watchtower:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_POLL_INTERVAL=86400
  #   restart: always

volumes:
  feed-icons:

networks:
  public_access: # Provide the access for ttrss UI
  service_only: # Provide the communication network between services only
    internal: true
  database_only: # Provide the communication between ttrss and database only
    internal: true
```

```
server {
    listen 80;
    server_name  ttrss.littlecorgi.top;
    return 301 https://ttrss.littlecorgi.top$request_uri;
}
server
{
	listen 443 ssl;
    gzip on;
    server_name  ttrss.littlecorgi.top;
    
    ssl_certificate    /www/server/panel/vhost/cert/ttrss.littlecorgi.top/fullchain.pem;
    ssl_certificate_key    /www/server/panel/vhost/cert/ttrss.littlecorgi.top/privkey.pem;
    
    access_log /www/server/nginx/ttrssdev_access.log combined;
    error_log  /www/server/nginx/ttrssdev_error.log;
    
    location / {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:9999;

        proxy_set_header  Host                $http_host;
        proxy_set_header  X-Real-IP           $remote_addr;
        proxy_set_header  X-Forwarded-Ssl     on;
        proxy_set_header  X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto   $scheme;
        proxy_set_header  X-Frame-Options     SAMEORIGIN;

        client_max_body_size        100m;
        client_body_buffer_size     128k;

        proxy_buffer_size           4k;
        proxy_buffers               4 32k;
        proxy_busy_buffers_size     64k;
        proxy_temp_file_write_size  64k;
    }
}
```

**Comment by dimon222** [comment]
Anything in `docker logs` for TTRSS container?

**Comment by littlecorgi-twk** [comment]
> Anything in `docker logs` for TTRSS container?

![image](https://user-images.githubusercontent.com/20331307/113475637-7c41c100-94a9-11eb-89d6-577483f7f66f.png)

but the password is correct。

![image](https://user-images.githubusercontent.com/20331307/113475698-cb87f180-94a9-11eb-8cd8-f7d00e3e1a10.jpeg)

**Comment by littlecorgi-twk** [comment]
> > Anything in `docker logs` for TTRSS container?
> 
> ![image](https://user-images.githubusercontent.com/20331307/113475637-7c41c100-94a9-11eb-89d6-577483f7f66f.png)
> 
> but the password is correct。
> 
> ![image](https://user-images.githubusercontent.com/20331307/113475698-cb87f180-94a9-11eb-8cd8-f7d00e3e1a10.jpeg)

```yml

# docker-compose.yml
version: "3"
services:
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 9999:80
    environment:
      - SELF_URL_PATH=https://ttrss.littlecorgi.top/ # please change to your own domain
      - DB_HOST=database.postgres
      - DB_PORT=5432
      - DB_NAME=ttrss
      - DB_USER=pgsql_ttrss
      - DB_PASS=ttrss385419 # please change the password
      - PUID=1000
      - PGID=1000
    volumes:
      - feed-icons:/var/www/feed-icons/
    networks:
      - public_access
      - service_only
      - database_only
    stdin_open: true
    tty: true
    restart: always

  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    networks:
      - public_access
      - service_only
    restart: always

  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      - NODE_ENV=production
    networks:
      - service_only
    restart: always

  database.postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=ttrss385419 # feel free to change the password
    volumes:
      - ~/postgres/data/:/var/lib/postgresql/data # persist postgres data to ~/postgres/data/ on the host
    networks:
      - database_only
    restart: always

  # utility.watchtower:
  #   container_name: watchtower
  #   image: containrrr/watchtower:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_POLL_INTERVAL=86400
  #   restart: always

volumes:
  feed-icons:

networks:
  public_access: # Provide the access for ttrss UI
  service_only: # Provide the communication network between services only
    internal: true
  database_only: # Provide the communication between ttrss and database only
    internal: true

```

**Comment by dimon222** [comment]
Try to update password for user and see if it helps. If you don't care about the data, you could start with fresh postgres.

**Comment by littlecorgi-twk** [comment]
I switched to a new database and updated the files. But it shows authentication failure...
```yml
# docker-compose.yml 

version: "3"
services:
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 9999:80
    environment:
      - SELF_URL_PATH=https://ttrss.littlecorgi.top/ # please change to your own domain
      - DB_HOST=database.postgres
      - DB_PORT=5432
      - DB_NAME=ttrss
      - DB_USER=ttrss
      - DB_PASS=Jjy06185419
      - PUID=1000
      - PGID=1000
    volumes:
      - feed-icons:/var/www/feed-icons/
    networks:
      - public_access
      - service_only
      - database_only
    stdin_open: true
    tty: true
    restart: always

  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    networks:
      - public_access
      - service_only
    restart: always

  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      - NODE_ENV=production
    networks:
      - service_only
    restart: always

  database.postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=Jjy06185419 # feel free to change the password
    volumes:
      - ~/postgres/data/:/var/lib/postgresql/data # persist postgres data to ~/postgres/data/ on the host
    networks:
      - database_only
    restart: always

  # utility.watchtower:
  #   container_name: watchtower
  #   image: containrrr/watchtower:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_POLL_INTERVAL=86400
  #   restart: always

volumes:
  feed-icons:

networks:
  public_access: # Provide the access for ttrss UI
  service_only: # Provide the communication network between services only
    internal: true
  database_only: # Provide the communication between ttrss and database only
    internal: true
```
---

```log
// log info

PDOException: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "ttrss" in /initialize.php:117
Stack trace:
#0 /initialize.php(117): PDO->__construct()
#1 /initialize.php(126): connectDatabase()
#2 /initialize.php(26): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "ttrss" in /initialize.php:117
Stack trace:
#0 /initialize.php(117): PDO->__construct()
#1 /initialize.php(126): connectDatabase()
#2 /initialize.php(26): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "ttrss" in /initialize.php:117
Stack trace:
#0 /initialize.php(117): PDO->__construct()
#1 /initialize.php(126): connectDatabase()
#2 /initialize.php(26): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "ttrss" in /initialize.php:117
Stack trace:
#0 /initialize.php(117): PDO->__construct()
#1 /initialize.php(126): connectDatabase()
#2 /initialize.php(26): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "ttrss" in /initialize.php:117
Stack trace:
#0 /initialize.php(117): PDO->__construct()
#1 /initialize.php(126): connectDatabase()
#2 /initialize.php(26): checkConnection()
```

**Comment by littlecorgi-twk** [comment]
I reconfigured it according to the [official website](http://ttrss.henry.wang/zh/#%E9%80%9A%E8%BF%87-docker-compose-%E9%83%A8%E7%BD%B2), and I still got this error

```yml
version: "3"
services:
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 9999:80
    environment:
      - SELF_URL_PATH=https://ttrss.littlecorgi.top/ # please change to your own domain
      - DB_PASS=abcdefgHIGK
      - PUID=1000
      - PGID=1000
    volumes:
      - feed-icons:/var/www/feed-icons/
    networks:
      - public_access
      - service_only
      - database_only
    stdin_open: true
    tty: true
    restart: always

  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    networks:
      - public_access
      - service_only
    restart: always

  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      - NODE_ENV=production
    networks:
      - service_only
    restart: always

  database.postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=abcdefgHIGK
    volumes:
      - ~/postgres/data/:/var/lib/postgresql/data # persist postgres data to ~/postgres/data/ on the host
    networks:
      - database_only
    restart: always

  # utility.watchtower:
  #   container_name: watchtower
  #   image: containrrr/watchtower:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_POLL_INTERVAL=86400
  #   restart: always

volumes:
  feed-icons:

networks:
  public_access: # Provide the access for ttrss UI
  service_only: # Provide the communication network between services only
    internal: true
  database_only: # Provide the communication between ttrss and database only
    internal: true
```
then `docker-compose down` and `docker-compose up -d`.

input `docker logs --since 30m ttrss -t`, then
```
2021-04-10T05:51:56.691178231Z PDOException: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "postgres" in /initialize.php:117
2021-04-10T05:51:56.691224880Z Stack trace:
2021-04-10T05:51:56.691228886Z #0 /initialize.php(117): PDO->__construct()
2021-04-10T05:51:56.691232121Z #1 /initialize.php(126): connectDatabase()
2021-04-10T05:51:56.691235721Z #2 /initialize.php(26): checkConnection()
2021-04-10T05:51:59.690850196Z #3 {main}PDOException: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "postgres" in /initialize.php:117
2021-04-10T05:51:59.690883833Z Stack trace:
2021-04-10T05:51:59.690887441Z #0 /initialize.php(117): PDO->__construct()
2021-04-10T05:51:59.690890503Z #1 /initialize.php(126): connectDatabase()
2021-04-10T05:51:59.690893179Z #2 /initialize.php(26): checkConnection()
2021-04-10T05:52:02.692785523Z #3 {main}PDOException: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "postgres" in /initialize.php:117
2021-04-10T05:52:02.692792838Z Stack trace:
2021-04-10T05:52:02.692795631Z #0 /initialize.php(117): PDO->__construct()
2021-04-10T05:52:02.692798389Z #1 /initialize.php(126): connectDatabase()
2021-04-10T05:52:02.692800941Z #2 /initialize.php(26): checkConnection()
2021-04-10T05:52:05.696912816Z #3 {main}PDOException: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "postgres" in /initialize.php:117
2021-04-10T05:52:05.696934005Z Stack trace:
2021-04-10T05:52:05.696938076Z #0 /initialize.php(117): PDO->__construct()
2021-04-10T05:52:05.696951349Z #1 /initialize.php(126): connectDatabase()
2021-04-10T05:52:05.696955341Z #2 /initialize.php(26): checkConnection()
2021-04-10T05:52:08.700826514Z #3 {main}PDOException: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "postgres" in /initialize.php:117
2021-04-10T05:52:08.700834098Z Stack trace:
2021-04-10T05:52:08.700837008Z #0 /initialize.php(117): PDO->__construct()
2021-04-10T05:52:08.700839832Z #1 /initialize.php(126): connectDatabase()
2021-04-10T05:52:08.700842458Z #2 /initialize.php(26): checkConnection()
```
