### ISSUE TITLE
URL使用域名加端口无法访问[BUG]

### ISSUE THREAD

**Issue by MatrixShoo** [HenryQW/Awesome-TTRSS#296]
**Bug 描述**
我是在家庭宽带下使用docker-compose搭建的，由于443端口运营商封闭，所以使用了别的端口，然后使用Nginx proxy manager进行反向代理，但是启动后检测一直有错误。
尝试过将地址更改为：http://ttrss.oo0oo.space:5820/ 或者 https://ttrss.oo0oo.space:5820均无法通过
且如果使用192.168.1.100:5820 就可以，但是反向代理后也是提示地址错误！

![image](https://user-images.githubusercontent.com/9585733/117102220-643eb500-ad67-11eb-8331-52a45fe7cf19.png)

**你谷歌/百度了吗？**
使用了，但是么有解决

**部署方法**
 - docker-compose
 - 使用的镜像版本 ：latest

**部署环境**
QNAP Container

**复现步骤**
复现该 bug 的详细步骤
1. 打开 '...'
2. 点击 '....'
3. 滑动至 '....'
4. 发现错误

**预期结果**
使用浏览器地址能够正常浏览

**截屏**
如果可以提供截屏将有助于 bug 修复。

**错误日志**

![image](https://user-images.githubusercontent.com/9585733/117102366-b4b61280-ad67-11eb-92cd-bd478cacb6ab.png)

**其他**
compose设置贴下：
```
version: "3"
services:
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 5820:80
    environment:
      - SELF_URL_PATH=https://ttrss.oo0oo.space:5820/ # please change to your own domain
      - DB_PASS=****** # use the same password defined in `database.postgres`
      - PUID=1000
      - PGID=1000
      - ALLOW_PORTS=1200,3000,5820
    volumes:
      - /share/Docker/TTRSS:/var/www/feed-icons/
    networks:
      - public_access
      - service_only
      - database_only
    stdin_open: true
    tty: true
    restart: always

  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    networks:
      - public_access
      - service_only
    restart: always

  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      - NODE_ENV=production
    networks:
      - service_only
    restart: always

  database.postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=****** # feel free to change the password
    volumes:
      - /share/Docker/Postgres:/var/lib/postgresql/data # persist postgres data to ~/postgres/data/ on the host
    networks:
      - database_only
    restart: always

  # utility.watchtower:
  #   container_name: watchtower
  #   image: containrrr/watchtower:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_POLL_INTERVAL=86400
  #   restart: always

volumes:
  feed-icons:

networks:
  public_access: # Provide the access for ttrss UI
  service_only: # Provide the communication network between services only
    internal: true
  database_only: # Provide the communication between ttrss and database only
    internal: true
```
