### ISSUE TITLE
ICONS_DIR defined in config.php is not writtable[BUG]

### ISSUE THREAD

**Issue by dupeliuhao** [HenryQW/Awesome-TTRSS#337]
**Describe the bug**
我按照官方的docker-compose.yml来setup。我只改了volume mount point和密码。我打开浏览器输入http://10.0.0.66:181
会提示我connection refuesed。 我尝试看了下ttrss log。log里有error：
```
PDOException: SQLSTATE[08006] [7] FATAL:  database "ttrss" does not exist in /initialize.php:155
Stack trace:
#0 /initialize.php(155): PDO->__construct()
#1 /initialize.php(164): connectDatabase()
#2 /initialize.php(73): checkConnection()
#3 {main}Database not found, creating.
Database table not found, applying schema... 
Please fix errors indicated by the following messages:
 * ICONS_DIR defined in config.php is not writable (chmod -R 777 feed-icons).
You might want to check tt-rss wiki or the forums for more information.
Please search the forums before creating new topic for your question.

```

**Have you googled?**
尝试google了很多。我只是储备不够但是。我猜这是一个PGID或者PUID setup的一个小问题。谢谢帮助啊！

**Deployment method**
 - docker-compose
 - latest

**Deployment environment**
 - OS: Ubuntu 20.04
 - Browser: chrome

**Error logs**
```
PDOException: SQLSTATE[08006] [7] FATAL:  database "ttrss" does not exist in /initialize.php:155
Stack trace:
#0 /initialize.php(155): PDO->__construct()
#1 /initialize.php(164): connectDatabase()
#2 /initialize.php(73): checkConnection()
#3 {main}Database not found, creating.
Database table not found, applying schema... 
Please fix errors indicated by the following messages:
 * ICONS_DIR defined in config.php is not writable (chmod -R 777 feed-icons).
You might want to check tt-rss wiki or the forums for more information.
Please search the forums before creating new topic for your question.

```

**Additional context**

我的docker-compose.yml文件已经贴了上来了。谢谢帮助！我是不是需要检查我的mount的这些目录的权限吗？Port 181已经在ufw 里allow了。应该不是防火墙的问题
```
version: "3"
services:
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 181:80
    environment:
      - SELF_URL_PATH=http://10.0.0.66:181/ # please change to your own domain
      - DB_PASS=XXXX # use the same password defined in `database.postgres`
      - PUID=1000
      - PGID=0
    volumes:
      - /home/dupeliuhao/ttrss_vol:/var/www/feed-icons/
    networks:
      - public_access
      - service_only
      - database_only
    stdin_open: true
    tty: true
    restart: always

  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    networks:
      - public_access
      - service_only
    restart: always

  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      - NODE_ENV=production
    networks:
      - service_only
    restart: always

  database.postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=XXXX # feel free to change the password
    volumes:
      - ~/postgres/data/:/var/lib/postgresql/data # persist postgres data to ~/postgres/data/ on the host
    networks:
      - database_only
    restart: always

  # utility.watchtower:
  #   container_name: watchtower
  #   image: containrrr/watchtower:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_POLL_INTERVAL=86400
  #   restart: always

volumes:
  feed-icons:

networks:
  public_access: # Provide the access for ttrss UI
  service_only: # Provide the communication network between services only
    internal: true
  database_only: # Provide the communication between ttrss and database only
    internal: true
```
