### ISSUE TITLE
[BUG]ttrss服务无法连接postgres。

### ISSUE THREAD

**Issue by Aquabet** [HenryQW/Awesome-TTRSS#406]
**Bug 描述**

使用[通过 docker-compose 部署](http://ttrss.henry.wang/zh/#%E9%80%9A%E8%BF%87-docker-%E9%83%A8%E7%BD%B2)，部署ttrss时，ttrss服务无法连接postgres，网站无法打开。

**部署方法**
 docker-compose: https://github.com/HenryQW/Awesome-TTRSS/blob/main/docker-compose.yml

**部署环境**
 - 操作系统: Ubuntu 20.04，使用了宝塔及宝塔自带的docker管理软件

**复现步骤**
下载了`docker-compose.yml`，运行`docker-compose up -d``。网站无法打开，查看日志如下错误日志。docker-compose.yml内容如下：

```
version: "3"
services:
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 181:80
    environment:
      - SELF_URL_PATH=mydomain.xxx.com #此处我马赛克了
      - DB_PASS=ovv01klyi6TczMUI
      - PUID=1000
      - PGID=1000
    volumes:
      - feed-icons:/var/www/feed-icons/
    networks:
      - public_access
      - service_only
      - database_only
    stdin_open: true
    tty: true
    restart: always

  service.mercury:
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    networks:
      - public_access
      - service_only
    restart: always

  service.opencc:
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      - NODE_ENV=production
    networks:
      - service_only
    restart: always

  database.postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=ovv01klyi6TczMUI
    volumes:
      - ~/postgres/data/:/var/lib/postgresql/data
    networks:
      - database_only
    restart: always


volumes:
  feed-icons:

networks:
  public_access:
  service_only:
    internal: true
  database_only:
    internal: true
```

**预期结果**
网站能打开。

**错误日志**
ttrss的错误日志

```
PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (192.168.0.3), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.postgres" (192.168.0.3), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
...一直循环这一段
```

postgres的错误日志
```
2022-07-24 20:26:01.515 UTC [29] FATAL:  password authentication failed for user "postgres"
2022-07-24 20:26:01.515 UTC [29] DETAIL:  Password does not match for user "postgres".
	Connection matched pg_hba.conf line 98: "host	all 		all		0.0.0.0/0		md5"
```
