### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EUye9IM** [HenryQW/Awesome-TTRSS#448]
**Bug 描述**
HTTP ERROR 503, ttrss 日志 timeout

**你谷歌/百度了吗？**
我看了一些 issue

**部署方法**
docker-compose

**日志**

```bash
❯ docker compose logs -f
postgres  |
postgres  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres  |
postgres  | 2023-03-12 14:33:12.982 UTC [1] LOG:  starting PostgreSQL 13.10 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
postgres  | 2023-03-12 14:33:12.983 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres  | 2023-03-12 14:33:12.983 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres  | 2023-03-12 14:33:12.985 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres  | 2023-03-12 14:33:12.989 UTC [22] LOG:  database system was shut down at 2023-03-12 14:30:39 UTC
postgres  | 2023-03-12 14:33:12.997 UTC [1] LOG:  database system is ready to accept connections
ttrss     | Operation timed out
ttrss exited with code 0
ttrss     | Operation timed out
ttrss exited with code 0
ttrss     | Operation timed out
ttrss exited with code 0
...
```

docker-compose.yml
```yaml
version: "3"
services:
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 10000:80
    environment:
      - SELF_URL_PATH=http://localhost:10000/ # please change to your own domain
      - DB_PASS=rss30312 # use the same password defined in `database.postgres`
      - PUID=1000
      - PGID=1000
    volumes:
      - feed-icons:/var/www/feed-icons/
    networks:
      - public_access
      - service_only
      - database_only
    stdin_open: true
    tty: true
    restart: always

      #  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
      #    image: wangqiru/mercury-parser-api:latest
      #    container_name: mercury
      #    networks:
      #      - public_access
      #      - service_only
      #    restart: always
      #
      #  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
      #    image: wangqiru/opencc-api-server:latest
      #    container_name: opencc
      #    environment:
      #      - NODE_ENV=production
      #    networks:
      #      - service_only
      #    restart: always

  database.postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=rss30312  # feel free to change the password
    volumes:
      - ~/postgres/data/:/var/lib/postgresql/data # persist postgres data to ~/postgres/data/ on the host
    networks:
      - database_only
    restart: always

  # utility.watchtower:
  #   container_name: watchtower
  #   image: containrrr/watchtower:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_POLL_INTERVAL=86400
  #   restart: always

volumes:
  feed-icons:

networks:
  public_access: # Provide the access for ttrss UI
  service_only: # Provide the communication network between services only
    internal: true
  database_only: # Provide the communication between ttrss and database only
    internal: true
```

总之docker确实用不太熟，postgres日志也看不太懂。

端口防火墙应该是开了的，docker外面 `nc -l` 可以监听到请求。
