### ISSUE TITLE
[BUG]我也遇到了operation time out

### ISSUE THREAD

**Issue by Adsryen** [HenryQW/Awesome-TTRSS#492]
**Describe the bug**
```
我之前是直接使用的你的compose文件，直接梭哈（正常使用），但是最近我有别的容器也会用到postgresql数据库，
我就把postgresql数据库分离出来了，作为一个单独的compose去管理postgresql，里面的账号数据这些都没动

然后修改了ttrss的compose与数据库地址信息之后，就重构容器ttrss后不正常了
```
**Have you googled?**
Please google it now.

**Deployment method**
 - Docker or docker-compose
 - Version of the image used [e.g. latest, nightly, 19.8]

## ttrss的compose：

```
version: "3"
services:
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 181:80
    environment:
      - SELF_URL_PATH=https://****.com/ # please change to your own domain
      - DB_HOST=postgres # 修改为新的数据库容器的服务名称
      - DB_PORT=5432
      - DB_NAME=ttrss # 修改为你的数据库名称
      - DB_USER=postgres # 修改为你的数据库用户名
      - DB_PASS=**** # 修改为你的数据库密码
      - PUID=1000
      - PGID=1000
      - SESSION_COOKIE_LIFETIME=72 # cookie 过期时间：小时
    volumes:
      - feed-icons:/var/www/feed-icons/
    stdin_open: true
    tty: true
    restart: always

  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    restart: always

  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      - NODE_ENV=production
    restart: always

volumes:
  feed-icons:

```
## postgres的compose（进容器后感觉正常使用）：
```
version: '3'
services:
    postgres:
        image: postgres:13-alpine
        container_name: postgres
        ports:
          - 5432:5432
        environment:
          - POSTGRES_PASSWORD=****  # feel free to change the password
        volumes:
          - /root/docker_data/postgres/data/:/var/lib/postgresql/data # persist postgres data to ~/postgres/data/ on the host
        restart: always
```

**Deployment environment**
 - OS: [e.g. Ubuntu 18.04]
 - Browser: [e.g. chrome, safari]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Error logs**
When the error occurs, execute `docker logs ttrss --tail 100` to obtain the error logs and paste **the relevant logs** here.

```
[root@linux ttrss]# docker compose logs
ttrss  | Operation timed out
ttrss  | Operation timed out
ttrss  | Operation timed out
ttrss  | Operation timed out
ttrss  | Operation timed out
ttrss  | Operation timed out
ttrss  | Operation timed out
ttrss  | Operation timed out
ttrss  | Operation timed out
ttrss  | Operation timed out
ttrss  | Operation timed out
ttrss  | Operation timed out
ttrss  | Operation timed out
```

```
ttrss=> \dt
                        关联列表
 架构模式 |           名称           |  型别  |  拥有者  
----------+--------------------------+--------+----------
 public   | ttrss_access_keys        | 资料表 | postgres
 public   | ttrss_app_passwords      | 资料表 | postgres
 public   | ttrss_archived_feeds     | 资料表 | postgres
 public   | ttrss_cat_counters_cache | 资料表 | postgres
..........
```

**Additional context**
