### ISSUE TITLE
[BUG] feed-icons mount point changed upstream without being reflected in docker-compose.yml

### ISSUE THREAD

**Issue by winneratwin** [HenryQW/Awesome-TTRSS#517]
**Describe the bug**
The feed-icons folder has changed from location in the docker-compose example.

https://gitlab.tt-rss.org/tt-rss/tt-rss/-/commit/a30b9bb649#4debf48ffbb605888365af7cf016170407384eca_1675_1691

**Have you googled?**
Yes

**Deployment method**
 - Docker Compose
 ```
 services:
  ttrss:
    image: wangqiru/ttrss
    restart: unless-stopped
    environment:
      - SELF_URL_PATH=https://rss.redacted.com/
      - DB_HOST=10.69.0.8
      - DB_PORT=5432
      - DB_NAME=tinytinyrss
      - DB_USER=redacted
      - DB_PASS=redacted
    volumes:
      - ./plugins:/var/www/plugins.local
      - ./cache:/var/www/cache/
      #- ./app:/var/www/
    networks:
      traefik:
        ipv4_address: 10.69.0.40



networks:
  traefik:
    external: true
```

**Deployment environment**
 - OS: raspberry pi os `Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
 - Browser: firefox

**To Reproduce**
1. launch image without changing `icons:/var/www/feed-icons/` to `icons:/var/www/cache/feed-icons/`  
2. add a feed with a icon
3. wait for it to fetch the icon
4. restart the container
5. see no icons

**Expected behavior**
The icons should be persistent

**Screenshots**
Screenshot of ttrss instance after restarting container having changed mount point to the correct point.
![image](https://github.com/HenryQW/Awesome-TTRSS/assets/32520794/67d2ae1e-fa9a-433a-a8ce-cefa7e284bc2)

**Error logs**
Would look like normal logs due to it being a persistence problem.

**Additional context**
Seems like you bumped the postgres version in docker-compose without realizing that the configuration was broken.
