### ISSUE TITLE
How can I update ttrss, which is installed from a docker, from crontab?

### ISSUE THREAD

**Issue by Rixcloudllnll** [HenryQW/Awesome-TTRSS#53]
- ## _What_ is the issue?

The minimum default update interval is 15 mins. I want to set to 5 mins. Although I found the approach from [official web](https://git.tt-rss.org/fox/tt-rss/wiki/UpdatingFeeds), it is not compatible for a docker 

```
*/30 * * * * /usr/bin/php /path/to/tt-rss/update.php --feeds --quiet
```

I DO NOT know how to find php and update.php in docker.

- ## _What_ is your OS and its version?

CENTOS 7

- ## _What_ is your installation method?

From your guide [https://ttrss.henry.wang/#deployment-via-docker-compose](https://ttrss.henry.wang/#deployment-via-docker-compose)

### Other Information

I already have a nonroot account just called non_root

```
docker ps
CONTAINER ID        IMAGE                                COMMAND                    NAMES
83d694be91d2        wangqiru/opencc-api-server:latest    "/bin/sh -c 'npm sta…"     opencc
b41a35b7cf87        sameersbn/postgresql:latest          "/sbin/entrypoint.sh"      postgres
bcbae28836c0        wangqiru/mercury-parser-api:latest   "dumb-init -- npm ru…"     mercury
951391b6436a        wangqiru/ttrss:latest                "sh -c 'sh /wait-for…"     ttrss
```

PHP
```
find / -name php
/var/lib/docker/overlay2/abbfabb773967bb2cc4b0b445fedc386bc40dc3a89eb4375929eb72730611fd8/merged/usr/bin/php
/var/lib/docker/overlay2/95a58411de262de8a7546ac279578d291694891c87781d3678bd2ed97b37b403/diff/usr/bin/php
```

## Thanks You

**Comment by Rixcloudllnll** [comment]
Do I have to set ```Default update interval:``` to ```Disable Update``` before I apply the crontab command?

**Comment by Rixcloudllnll** [comment]
My docker-compose.yml
```
version: "3"
services:
  database.postgres:
    image: sameersbn/postgresql:latest
    container_name: postgres
    environment:
      - PG_PASSWORD=hidden # please change the password
      - DB_EXTENSION=pg_trgm
    volumes:
      - ~/postgres/data/:/var/lib/postgresql/ # persist postgres data to ~/postgres/data/ on the host
    restart: always

  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - port_hidden:80
    environment:
      - SELF_URL_PATH=hidden # please change to your own domain
      - DB_HOST=database.postgres
      - DB_PORT=5432
      - DB_NAME=ttrss
      - DB_USER=postgres
      - DB_PASS=hidden # please change the password
      - SESSION_COOKIE_LIFETIME=8760 #  one year
      - ENABLE_PLUGINS=auth_internal,fever # auth_internal is required. Plugins enabled here will be enabled for all users as system plugins
    stdin_open: true
    tty: true
    restart: always
    command: sh -c 'sh /wait-for.sh database.postgres:5432 -- php /configure-db.php && exec s6-svscan /etc/s6/'

  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    expose:
      - 3000
    restart: always

  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      NODE_ENV: production
    expose:
      - 3000
    restart: always
```
---
One more question, after I editing docker-compose.yml, can I just run ```docker-compose up -d``` to update the ttrss ? Or I have to run ```docker stop 951391b6436a ``` first ?
