### ISSUE TITLE
[Feature]  ICONS_DIR權限問題解決辦法

### ISSUE THREAD

**Issue by vi000246** [HenryQW/Awesome-TTRSS#556]
**该功能能够解决的问题**

依據這篇issue https://github.com/HenryQW/Awesome-TTRSS/issues/466
在synology 群暉的nas遇到 ICONS_DIR defined in config.php is not writable (chmod -R 777 feed-icons).

**形容理想的解决方案**
用busybox將/feed-icons給予權限
我這個compose file的path是適用於synology nas的

以下是docker compose file
```
services:
  init-feed-icons:
    image: busybox
    volumes:
      - /volume1/docker/ttrss/feed-icons:/feed-icons
    command: ["sh", "-c", "chmod -R 777 /feed-icons"]
    networks:
      - service_only
    restart: "no"
    
  ttrss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - "181:80"
    environment:
      - SELF_URL_PATH=http://localhost:181
      - DB_PASS=pass
      - PUID=1026
      - PGID=100
    volumes:
      - /volume1/docker/ttrss/feed-icons:/var/www/feed-icons/
    networks:
      - public_access
      - service_only
      - database_only
    stdin_open: true
    tty: true
    depends_on:
      - init-feed-icons
      - database.postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 5


  mercury:
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    networks:
      - public_access
      - service_only
    restart: always

  opencc:
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      - NODE_ENV=production
    networks:
      - service_only
    restart: always

  database.postgres:
    image: postgres:16-alpine

    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
      - /volume1/docker/ttrss/postgres-data:/var/lib/postgresql/data
    networks:
      - database_only
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 5

  rsshub:
    container_name: rsshub
    image: diygod/rsshub:latest
    environment:
      NODE_ENV: production
      DEBUG_INFO: false
      LOGGER_LEVEL: error
      NO_LOGFILES: true    
    networks:
      - service_only
    ports:
      - "1200:3000"
    restart: unless-stopped

volumes:
  feed-icons:

networks:
  public_access:
  service_only:
    internal: true
  database_only:
    internal: true
```
