### ISSUE TITLE
[Feature]希望添加树莓派等armv32/arm64设备支持

### ISSUE THREAD

**Issue by virualv** [HenryQW/Awesome-TTRSS#88]
> 目前大都是基于x86/x64编写的docker-compose.yml，无法在树莓派中直接使用，自己尝试修改过docker-compose.yml，但是发现无法更新源的信息，单一部署ttrss和postgres可以使用，但重启容器后还是出现无法更新的情况。

> 希望可以添加添加armv32/arm64支持。

*具体docker-compose.yml，麻烦帮忙看看，谢谢*
```yaml
---
version: "2"
services:
  service.postgresql:
    image: postgres:10-alpine
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ttrss
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./data/var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - rssnet

  service.ttrss:
    image: linuxserver/tt-rss:arm32v7-latest
    container_name: tt-rss
    ports:
      - 2080:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./data/config/ttrss:/config
    restart: always
    networks:
      - rssnet

  service.rsshub:
    image: pjf1996/rsshub:arm32v7
    container_name: rsshub
    ports:
      - 1200:1200
    restart: always
    networks:
      - rssnet

networks:
  rssnet:
    driver: "bridge"
```
